"""Error code constants for Jarvis CLI."""

LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
TIMEOUT = "TIMEOUT"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_REQUEST = "INVALID_REQUEST"
ENGINE_UNAVAILABLE = "ENGINE_UNAVAILABLE"
INTERNAL_ERROR = "INTERNAL_ERROR"
